### ISSUE TITLE
Helm Multi Environments Release Deployment

### ISSUE THREAD

**Issue by olegterasky** [BENMALEKarim/helm-course-issues-tracker#1]
Hi
- In the scenario you ask to deploy hpa only when the namespace is prod-ns which is not a common practice
- In the check command you add additional parameter called environment which indeed is common practice 
- so IMHO need to create the HPA manifest as follows:
```yaml
{{- if eq .Values.environment "prod" }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
```
